resolver: lts-14.7

packages:
- '.'

extra-deps:
- ../netlist/netlist
# - netlist-0.4.0
- ../netlist/netlist-to-vhdl
# - netlist-to-vhdl-0.4.0
- ../sized-types
# - sized-types-0.5.1

flags: {}

extra-package-dbs: []
